# .travis.yml
language: ruby
cache: 
  bundler: true
  apt: true
  directories: 
    - vendor/geolite
services: 
  - redis-server
rvm:
  - 2.2.2
before_install:
  - gem update --system
  - sudo apt-get install sphinxsearch
  - cd vendor/geolite/ && wget --quiet --output-document gelolite.download.log http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz -O GeoLiteCity.dat.gz && gunzip GeoLiteCity.dat.gz && cd -
script:
  - RAILS_ENV=test bundle exec rake db:drop db:create db:schema:load 
  - mkdir -p tmp/cache
  - cp config/initializers/localeapp.rb.travis config/initializers/localeapp.rb
  - RAILS_ENV=test bundle exec rake ts:configure
  - RAILS_ENV=test bundle exec rake ts:index
  - RAILS_ENV=test bundle exec rake ts:start
  - bundle exec rake db:test:prepare
  - bundle exec rake test
before_script:
  - mysql -e 'create database nolotirov3_test;'
  - cp config/secrets.yml.example config/secrets.yml
  - cp config/database.yml.travis config/database.yml
env:
  - DATABASE=mysql2 SPHINX_BIN=/usr/bin/ SPHINX_VERSION=2.0.4
